clc
clear
close all




data_sets={'abalone.csv'
'acute-inflammation.csv'
'acute-nephritis.csv'
'adult_train.csv'
'annealing_train.csv'
'arrhythmia.csv'
'audiology-std_train.csv'
'balance-scale.csv'
'balloons.csv'
'bank.csv'
'blood.csv'
'breast-cancer-wisc-diag.csv'
'breast-cancer-wisc-prog.csv'
'breast-cancer-wisc.csv'
'breast-cancer.csv'
'breast-tissue.csv'
'car.csv'
'cardiotocography-10clases.csv'
'cardiotocography-3clases.csv'
'chess-krvk.csv'
'chess-krvkp.csv'
'congressional-voting.csv'
'conn-bench-sonar-mines-rocks.csv'
'conn-bench-vowel-deterding_train.csv'
'connect-4.csv'
'contrac.csv'
'credit-approval.csv'
'cylinder-bands.csv'
'dermatology.csv'
'echocardiogram.csv'
'ecoli.csv'
'energy-y1.csv'
'energy-y2.csv'
'fertility.csv'
'flags.csv'
'glass.csv'
'haberman-survival.csv'
'hayes-roth_train.csv'
'heart-cleveland.csv'
'heart-hungarian.csv'
'heart-switzerland.csv'
'heart-va.csv'
'hepatitis.csv'
'hill-valley_train.csv'
'horse-colic_train.csv'
'ilpd-indian-liver.csv'
'image-segmentation_train.csv'
'ionosphere.csv'
'iris.csv'
'led-display.csv'
'lenses.csv'
'letter.csv'
'libras.csv'
'low-res-spect.csv'
'lung-cancer.csv'
'lymphography.csv'
'magic.csv'
'mammographic.csv'
'miniboone.csv'
'molec-biol-promoter.csv'
'molec-biol-splice.csv'
'monks-1_train.csv'
'monks-2_train.csv'
'monks-3_train.csv'
'mushroom.csv'
'musk-1.csv'
'musk-2.csv'
'nursery.csv'
'oocytes_merluccius_nucleus_4d.csv'
'oocytes_merluccius_states_2f.csv'
'oocytes_trisopterus_nucleus_2f.csv'
'oocytes_trisopterus_states_5b.csv'
'optical_train.csv'
'ozone.csv'
'page-blocks.csv'
'parkinsons.csv'
'pendigits_train.csv'
'pima.csv'
'pittsburg-bridges-MATERIAL.csv'
'pittsburg-bridges-REL-L.csv'
'pittsburg-bridges-SPAN.csv'
'pittsburg-bridges-T-OR-D.csv'
'pittsburg-bridges-TYPE.csv'
'planning.csv'
'plant-margin.csv'
'plant-shape.csv'
'plant-texture.csv'
'post-operative.csv'
'primary-tumor.csv'
'ringnorm.csv'
'seeds.csv'
'semeion.csv'
'soybean_train.csv'
'spambase.csv'
'spect_train.csv'
'spectf_train.csv'
'statlog-australian-credit.csv'
'statlog-german-credit.csv'
'statlog-heart.csv'
'statlog-image.csv'
'statlog-landsat_train.csv'
'statlog-shuttle_train.csv'
'statlog-vehicle.csv'
'steel-plates.csv'
'synthetic-control.csv'
'teaching.csv'
'thyroid_train.csv'
'tic-tac-toe.csv'
'titanic.csv'
'trains.csv'
'twonorm.csv'
'vertebral-column-2clases.csv'
'vertebral-column-3clases.csv'
'wall-following.csv'
'waveform-noise.csv'
'waveform.csv'
'wine-quality-red.csv'
'wine-quality-white.csv'
'wine.csv'
'yeast.csv'
'zoo.csv'};

n_data = length(data_sets);

for n = 1:n_data
  data = load(['~/Git/ClassificationDatasets/csv/', data_sets{n}]);
  nf = size(data,2)-1;
  ns = size(data,1);
  nc = length(unique(data(:,end)));
  if nc >= 3
  %disp([data_sets{n}, '      NF:', num2str(nf), '      NC:', num2str(nc), '      NS:', num2str(ns)])
  disp(data_sets{n});
  end
end

